const TMDB_URL = process.env.EXPO_PUBLIC_TMDB_URL;
const TMDB_IMG_URL = process.env.EXPO_PUBLIC_TMDB_IMG_URL;
const TMDB_API_KEY = process.env.EXPO_PUBLIC_TMDB_API_KEY;
const TMDB_API_TOKEN = process.env.EXPO_PUBLIC_TMDB_API_TOKEN;

const YOUTUBE_URL = process.env.EXPO_PUBLIC_YOUTUBE_URL;
const YOUTUBE_API_KEY = process.env.EXPO_PUBLIC_YOUTUBE_API_KEY;

export { 
    TMDB_URL, TMDB_IMG_URL, TMDB_API_KEY, TMDB_API_TOKEN, YOUTUBE_URL, YOUTUBE_API_KEY,
}